# Generated by Django 2.1.1 on 2018-12-22 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181222_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_color',
            name='slug',
        ),
        migrations.AddField(
            model_name='product_color',
            name='size_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
