# Generated by Django 2.1.1 on 2018-12-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181222_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product_size',
            name='name',
        ),
        migrations.DeleteModel(
            name='Product_color',
        ),
        migrations.DeleteModel(
            name='Product_size',
        ),
    ]
