# Generated by Django 2.1.1 on 2018-12-22 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='T_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('card_pass', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('name_second', models.CharField(max_length=20)),
                ('self_ID', models.CharField(max_length=18, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AddField(
            model_name='t_card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.T_user', to_field='account'),
        ),
    ]
